# Site settings
title: Bautista Anglers
email: bautistaanglers@gmail.com
icon:
url: https://bautistaanglers.com
enforce_ssl: bautistaanglers.com
description: Bautista Anglers is a family-owned charter business out of Channel Islands Harbor in Oxnard, California.  We provide many services to several locations at a very good price.
about: Bautista Anglers is a family-owned business that wants to make the joy of fishing, available to all.  We have been fishing and navigating these waters for over 30 years, and want the opportunity to share our experience with you.
                           Whether you are looking to fish, go on a private whale watching tour, or simply check out the islands;
                           We are here to help.
address: Channel Islands Harbor<br>Oxnard, CA 93035
phone: (805)382-6951
keywords:
  - Fishing
  - Bautista
  - Harbor
  - Anglers
  - Channel Islands
  - Oxnard
  - Whale Watching
  - Ventura County
  - Camarillo
  - Ventura
  - Kayak
  - Channel Islands
  - Anacappa
  - Santa Rosa
  - San Miguel
  - San Nicolaus
  - Santa Cruz
  - Islands
  - Family
  - Cheap
  - Inexpensive
  - Charters

banner-services:
  - Fishing Charters
  - Whale Watching
  - Coastal Tours
  - Kayak Fishing

fonts:
  special: Lobster Two
  heading: Cabin
  content:

collections:
  services:
    output: false
  locations:
  photosections:
  boats:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/bautistaanglers/
  - title: facebook
    url:

# Footer settings
footer:
  copyright: Gregory Ball
  location: Contact Details
  social: Around the Web
  credits: Credits

color:
  menu-primary: 305F67
  menu-secondary: 00797C
  page-primary: 26454c
  page-secondary: white
